-- Phase 1: Freeze legacy canonical tables (reversible, non-destructive)
-- Do not run until Phase 0 dependency map is reviewed.

begin;

create table if not exists public._migration_log (
  id bigint generated by default as identity primary key,
  phase text not null,
  action text not null,
  detail jsonb not null default '{}'::jsonb,
  executed_by text not null default current_user,
  executed_at timestamptz not null default now()
);

do $$
declare
  rec record;
begin
  for rec in
    select *
    from (values
      ('routes', '_legacy_routes'),
      ('segments', '_legacy_segments'),
      ('events', '_legacy_events'),
      ('event_routes', '_legacy_event_routes'),
      ('event_route_segments', '_legacy_event_route_segments'),
      ('event_series', '_legacy_event_series'),
      ('route_pois', '_legacy_route_pois')
    ) as m(old_name, new_name)
  loop
    if to_regclass(format('public.%I', rec.old_name)) is not null then
      if to_regclass(format('public.%I', rec.new_name)) is not null then
        raise exception 'Target table already exists: %', rec.new_name;
      end if;
      execute format('alter table public.%I rename to %I', rec.old_name, rec.new_name);
    end if;
  end loop;
end $$;

do $$
declare
  t text;
begin
  foreach t in array array[
    '_legacy_routes',
    '_legacy_segments',
    '_legacy_events',
    '_legacy_event_routes',
    '_legacy_event_route_segments',
    '_legacy_event_series',
    '_legacy_route_pois'
  ]
  loop
    if to_regclass(format('public.%I', t)) is not null then
      execute format('revoke insert, update, delete on table public.%I from public, anon, authenticated, service_role', t);
      execute format('grant select on table public.%I to anon, authenticated, service_role', t);
      execute format(
        'comment on table public.%I is %L',
        t,
        'DEPRECATED: legacy canonical table frozen during migration to suc-shared-data. Read-only; scheduled for future retirement.'
      );
    end if;
  end loop;
end $$;

insert into public._migration_log (phase, action, detail)
values (
  'phase1-freeze',
  'legacy_canonical_freeze_complete',
  jsonb_build_object(
    'frozen_at', now(),
    'tables', jsonb_build_array(
      '_legacy_routes',
      '_legacy_segments',
      '_legacy_events',
      '_legacy_event_routes',
      '_legacy_event_route_segments',
      '_legacy_event_series',
      '_legacy_route_pois'
    ),
    'writes_revoked_for_roles', jsonb_build_array('public','anon','authenticated','service_role'),
    'select_retained_for_roles', jsonb_build_array('anon','authenticated','service_role')
  )
);

commit;

