-- Phase 6: Lock Supabase from canonical use (post-broadcast verification)
-- Non-destructive: does not drop legacy tables.

begin;

create table if not exists public._migration_log (
  id bigint generated by default as identity primary key,
  phase text not null,
  action text not null,
  detail jsonb not null default '{}'::jsonb,
  executed_by text not null default current_user,
  executed_at timestamptz not null default now()
);

do $$
declare
  t text;
begin
  foreach t in array array[
    '_legacy_routes',
    '_legacy_segments',
    '_legacy_events',
    '_legacy_event_routes',
    '_legacy_event_route_segments',
    '_legacy_event_series',
    '_legacy_route_pois'
  ]
  loop
    if to_regclass(format('public.%I', t)) is not null then
      execute format('revoke select on table public.%I from service_role', t);
      execute format(
        'comment on table public.%I is %L',
        t,
        'DEPRECATED + LOCKED: canonical source moved to suc-shared-data. Table retained only for audit/rollback. Marked for drop in a future migration.'
      );
    end if;
  end loop;
end $$;

do $$
declare
  fn record;
begin
  for fn in
    select
      n.nspname as schema_name,
      p.proname as function_name,
      pg_get_function_identity_arguments(p.oid) as function_args,
      p.oid as function_oid
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and (
        pg_get_functiondef(p.oid) ilike '%_legacy_routes%'
        or pg_get_functiondef(p.oid) ilike '%_legacy_segments%'
        or pg_get_functiondef(p.oid) ilike '%_legacy_events%'
        or pg_get_functiondef(p.oid) ilike '%_legacy_event_routes%'
        or pg_get_functiondef(p.oid) ilike '%_legacy_event_route_segments%'
        or pg_get_functiondef(p.oid) ilike '%_legacy_event_series%'
        or pg_get_functiondef(p.oid) ilike '%_legacy_route_pois%'
        or pg_get_functiondef(p.oid) ilike '% public.routes %'
        or pg_get_functiondef(p.oid) ilike '% public.segments %'
        or pg_get_functiondef(p.oid) ilike '% public.events %'
        or pg_get_functiondef(p.oid) ilike '% public.event_routes %'
        or pg_get_functiondef(p.oid) ilike '% public.event_route_segments %'
        or pg_get_functiondef(p.oid) ilike '% public.event_series %'
        or pg_get_functiondef(p.oid) ilike '% public.route_pois %'
      )
  loop
    execute format(
      'revoke execute on function %I.%I(%s) from service_role',
      fn.schema_name,
      fn.function_name,
      fn.function_args
    );

    insert into public._migration_log (phase, action, detail)
    values (
      'phase6-lock',
      'rpc_execute_revoked',
      jsonb_build_object(
        'function_schema', fn.schema_name,
        'function_name', fn.function_name,
        'function_args', fn.function_args
      )
    );
  end loop;
end $$;

create or replace view public.canonical_legacy_deprecation_notice as
select
  now() as notice_generated_at,
  'Canonical data access in Supabase is deprecated and locked.'::text as message,
  'Use suc-shared-data Git canonical JSON as source of truth.'::text as action_required,
  'Legacy tables are retained only for audit/rollback until formal drop migration is approved.'::text as retention_status;

grant select on public.canonical_legacy_deprecation_notice to anon, authenticated, service_role;

insert into public._migration_log (phase, action, detail)
values (
  'phase6-lock',
  'legacy_canonical_locked',
  jsonb_build_object(
    'locked_at', now(),
    'select_revoked_from', jsonb_build_array('service_role'),
    'tables_marked_for_future_drop', jsonb_build_array(
      '_legacy_routes',
      '_legacy_segments',
      '_legacy_events',
      '_legacy_event_routes',
      '_legacy_event_route_segments',
      '_legacy_event_series',
      '_legacy_route_pois'
    )
  )
);

commit;

